### ISSUE TITLE
SystemError bad argument to internal function with PyYAML > 5.1

### ISSUE THREAD

**Issue by marekvi95** [yukihiko-shinoda/yaml-dataclass-config#20]
Hello, I have an issue with PyYAML version > 5.1. When importing YamlDataClassConfig.
`from yamldataclassconfig.config import YamlDataClassConfig`

`Traceback (most recent call last):
  File "C:/Users/nxf46245/hwf_connector/src/hwf_connector/device_descriptor.py", line 10, in <module>
    from yamldataclassconfig.config import YamlDataClassConfig
  File "C:\Users\nxf46245\hwf_connector\venv\lib\site-packages\yamldataclassconfig\__init__.py", line 4, in <module>
    from yamldataclassconfig.config import *  # noqa
  File "C:\Users\nxf46245\hwf_connector\venv\lib\site-packages\yamldataclassconfig\config.py", line 7, in <module>
    import yaml
  File "C:\Users\nxf46245\hwf_connector\venv\lib\site-packages\yaml\__init__.py", line 13, in <module>
    from .cyaml import *
  File "C:\Users\nxf46245\hwf_connector\venv\lib\site-packages\yaml\cyaml.py", line 7, in <module>
    from _yaml import CParser, CEmitter
SystemError: c:\_work\14\s\objects\codeobject.c:121: bad argument to internal function`

It works fine with PyYAML versions lower <= 5.1. I have installed the package from the pip repository.

Environment: 
Windows 10 1909 x64
Python 3.8.0a4 x64
yamldataclassconfig 1.5.0

**Comment by yukihiko-shinoda** [comment]
Isn't it possible to update Python version?

It does not relate with YAML Dataclass Config,
it is caused by combination of PyYAML and Python 3.8.0a4 (and OS).

test.py:

```python
import yaml

print("Hello")
```

```console
$ pipenv run python --version
Python 3.8.0a4
$ pipenv run python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import yaml
  File "C:\Users\master\.virtualenvs\yaml-dataclass-config-ZV7SbUfH\lib\site-packages\yaml\__init__.py", line 13, in <module>
    from .cyaml import *
  File "C:\Users\master\.virtualenvs\yaml-dataclass-config-ZV7SbUfH\lib\site-packages\yaml\cyaml.py", line 7, in <module>
    from yaml._yaml import CParser, CEmitter
SystemError: c:\_work\14\s\objects\codeobject.c:121: bad argument to internal function
```

**Comment by marekvi95** [comment]
I've updated Python to the lastest 3.8 release and it works :) I didn't even notice that I was using pre-release version of Python. Thanks.
